name: deploy-lambda
description: Lambda関数にコンテナイメージをデプロイします。
inputs:
  function-name:
    required: true
    description: Lambda関数名
  image-url:
    required: true
    description: デプロイするコンテナイメージのURI
runs:
  using: composite
  steps:
    - run: |
        echo "Lambda関数 ${FUNCTION_NAME} にイメージ ${IMAGE_URI} をデプロイしています..."
        aws lambda update-function-code \
          --function-name "${FUNCTION_NAME}" \
          --image-uri "${IMAGE_URI}"

        echo "デプロイが完了するまで待機しています..."
        aws lambda wait function-updated \
          --function-name "${FUNCTION_NAME}"

        echo "Lambda関数のデプロイが完了しました"
      env:
        FUNCTION_NAME: ${{ inputs.function-name }}
        IMAGE_URI: ${{ inputs.image-url }}
      shell: bash
